<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>$(Version)</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Reactive" Version="7.0.0-preview.1" />
        
        <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <Target Name="ConfigureTrimming" BeforeTargets="PrepareForILLink">
        <ItemGroup>
            <ManagedAssemblyToLink Condition="'%(Filename)' == 'FSharp.Control.Reactive'">
                <TrimMode>link</TrimMode>
                <IsTrimmable>true</IsTrimmable>
            </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
    
    <ItemGroup>
        <Compile Include="Disposable.fs" />
        <Compile Include="Scheduler.fs" />
        <Compile Include="Subject.fs" />
        <Compile Include="Observer.fs" />
        <Compile Include="Dsl.fs" />
        <Compile Include="Observable.fs" />
        <Compile Include="Observable.Generators.fs" />
        <Compile Include="Observable.Filters.fs" />
        <Compile Include="Observable.Transformation.fs" />
        <Compile Include="Observable.Aggregation.fs" />
        <Compile Include="Observable.Partitioning.fs" />
        <Compile Include="Observable.Combinators.fs" />
        <Compile Include="Observable.TimeBased.fs" />
        <Compile Include="Observable.ErrorHandling.fs" />
        <Compile Include="Observable.Publishing.fs" />
        <Compile Include="Observable.Extra.fs" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Update="FSharp.Core" Version="10.1.203" />
    </ItemGroup>
    
</Project>
