<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="CancellableStream.fs" />
    <Compile Include="AppConfig.fs" />
    <Compile Include="Abstractions.fs" />
    <Compile Include="FileStorage.fs" />
    <Compile Include="AppSubject.fs" />
    <Compile Include="LogSource.fs" />
    <Compile Include="LogRepository.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\_libs\p1eXu5.FSharp.Reactive\src\p1eXu5.FSharp.Reactive\p1eXu5.FSharp.Reactive.fsproj" />
    <ProjectReference Include="..\LogParser\LogParser.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

</Project>
