<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Utilities\ShouldExtensions.fs" />
    <Compile Include="Utilities\MockLoggerFactory.fs" />
    <Compile Include="Types\TechJsonLogFieldTests.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.PrimitiveFieldCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.SpecialFieldCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.ArrayFieldCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.ArrayJsonAnnonimousCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.ArrayJsonCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.ArrayJsonAnnotatedCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.JsonFieldCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.JsonAnnotatedValueCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.JsonAnnotatedCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.BodyCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.MessageJsonListCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.MessageStringCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.MessageCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.MessageBodiedCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.MessageBodiedWithPostfixCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.ParseCases.fs" />
    <Compile Include="TechLogParserTests\TechLogParserTests.fs" />
    <Compile Include="KibanaTests.fs" />
    <Compile Include="CsvTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Faqt" Version="5.1.0" />
    <PackageReference Include="FsUnit" Version="7.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\_forks\FSharp.Control.Reactive\src\FSharp.Control.Reactive.Testing\FSharp.Control.Reactive.Testing.fsproj" />
    <ProjectReference Include="..\..\src\LogParser\LogParser.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.203" />
  </ItemGroup>

</Project>
