<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>$(Version)</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Reactive.Testing" Version="7.0.0-preview.1" />
        <PackageReference Include="FsCheck" Version="3.3.2" />
        <PackageReference Include="FParsec" Version="2.0.0-beta2" />
        <PackageReference Include="Unquote" Version="7.0.1" />
      
      <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>

      <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="TestNotifications.fs" />
        <Compile Include="TestSchedule.fs" />
        <Compile Include="TestObservable.fs" />
        <Compile Include="TestObserver.fs" />
        <Compile Include="Marbles.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\FSharp.Control.Reactive\FSharp.Control.Reactive.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="FSharp.Core" Version="10.1.203" />
    </ItemGroup>

</Project>
