<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Interfaces.fs" />
    <Compile Include="Helpers.fs" />
    <Compile Include="TextLogModel.fs" />
    <Compile Include="TechFieldModel.fs" />
    <Compile Include="TechJsonLogModel.fs" />
    <Compile Include="FiltersModel.fs" />
    <Compile Include="KibanaSearchModel.Services.fs" />
    <Compile Include="KibanaSearchModel.fs" />
    <Compile Include="JsonLogModelV2.fs" />
    <Compile Include="TextLogModelV2.fs" />
    <Compile Include="techlogmodel\TechLogModel.fs" />
    <Compile Include="TechLogModel\TechLogModel.Program.fs" />
    <Compile Include="TechLogModel\TechLogModel.Bindings.fs" />
    <Compile Include="TechLogListModel\TechLogListModel.fs" />
    <Compile Include="LogFileModel\LogFileModel.fs" />
    <Folder Include="LogFileListModel\" />
    <Compile Include="logfilelistmodel\LogFileListModel.fs" />
    <Compile Include="MainModel\MainModel.fs" />
    <Compile Include="MainModel\MainModel.Program.fs" />
    <Compile Include="MainModel\MainModel.Bindings.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elmish.WPF" Version="4.0.0-beta-56" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
    <PackageReference Include="p1eXu5.FSharp.ElmishExtensions" Version="1.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogParser.App\LogParser.App.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

</Project>
